### ISSUE TITLE
[Misc] Old Versions of FrankenHUD for archival-sake?

### ISSUE THREAD

**Issue by HeteroChromia420** [TheKins/frankenhud#100]
Title. not exactly an improvement to the current HUD, but an idea came to mind as i occasionally try a older build of TF2. Would it be feasable to include Old Versions of FrankenHUD as (maybe) Releases for the sake of keeping them archived?

**Comment by TheKins** [comment]
Looking at a long-forgotten corner of my web hosting, I have zip files for releases 42 (June 2012) through 65 (July 2015). Anything before that can be considered lost, everything after that was done on GitHub.

**Comment by HeteroChromia420** [comment]
i see. yeah that'll be good enough i guess.

**Comment by Kruphixx** [comment]
You can look through the list of commits and see very old versions/branches that way. Example: https://github.com/TheKins/frankenhud/tree/1959dd1675e97865d6735990e6a2cc825843c0d5
