### ISSUE TITLE
[Suggestion/Discussion] Default team status display

### ISSUE THREAD

**Issue by SchneiderAFX** [TheKins/frankenhud#103]
As the title implies. I would be cool to have an option to enable the default team status display in this hud.

**Comment by Kruphixx** [comment]
Deleting hudmatchstatus.res should technically work I think? If not I'll see what I can come up with.

**Comment by SchneiderAFX** [comment]
i actually tried that, but some panels are still visible and some gamemodes are quite broken like KOTH

**Comment by Kruphixx** [comment]
Sorry for the delay, been busy with other projects and things. Added it as a customization option.

To install it, replace the default hudlayout.res file with the one from the customization folder. **Also remove the following files:**

- hudmatchstatus.res
- hudobjectivekothtimepanel.res
- hudobjectivestatus.res
- hudobjectivetimepanel.res
