### ISSUE TITLE
[Addons/Old Scoreboard] Spectator count overlaps server label

### ISSUE THREAD

**Issue by Whurrhurr** [TheKins/frankenhud#104]
title. they have the same ypos. you could move the spectator count up, but then it overlaps the "Spectators in Queue" text. and you don't really have enough room to move the spectators in queue text up as well, because then it bleeds into the blue team playercount (and red team's, if there's enough spectators in the queue) so moving it to the eastern side of the scoreboard above the "Server map time left" text is the next best thing you can do.

**Comment by Kruphixx** [comment]
Got a screenshot?

**Comment by Whurrhurr** [comment]
![image](https://github.com/TheKins/frankenhud/assets/33162051/8cdccd78-a139-4998-a423-ae9c0067c55f)
depending on the length of usernames, it can clip into the server name label.
i've made some changes on my end to make it look like this
![image](https://github.com/TheKins/frankenhud/assets/33162051/3ea01282-afc2-4d46-b762-0095bbccd814)
changes made:
the ypos for spectators in mvm is set to "218" (this puts it between the player list panel and the credits breakdown panel)
![image](https://github.com/TheKins/frankenhud/assets/33162051/222d073e-f634-49c3-964e-e195f39e8314)
the ypos for spectators outside of mvm is "348" which is the same as SpectatorsInQueue (though i'm not sure if both of these can ever be used at once)
the xpos for ServerLabel is set to "12" because servers with really long names could overlap the "Server map time left" text if the server uses mp_timelimit and the server map time has run out)
BluePlayerList and RedPlayerList have had their "tall" set to "282" so that the avatar of the 16th player on both teams would not get cut off when playing on smaller resolutions
the VerticalLine has had it's "tall" lowered to "272" to accommodate the changes made to Spectators' ypos

**Comment by Kruphixx** [comment]
Hm, any chance you could do a pull request with the changes you made?

**Comment by Whurrhurr** [comment]
[Old Scoreboard.zip](https://github.com/user-attachments/files/15942062/Old.Scoreboard.zip)

here's the .res file zipped up.

**Comment by Kruphixx** [comment]
I suppose that works too. Thank you!
