### ISSUE TITLE
[Bug] spectatortournament has misplaced red team panels in Mann vs Machine

### ISSUE THREAD

**Issue by Whurrhurr** [TheKins/frankenhud#105]
title. this is what it looks like:
![frankenhud spectatortournament](https://github.com/TheKins/frankenhud/assets/33162051/02e3d0e5-cfce-44ed-90f7-30638fe546af)

 adding
"team1_player_delta_y"			"0"
to the "if_mvm" check right above the "topbar" entry will fix this

**Comment by Kruphixx** [comment]
I assume you tested this so I will trust you on this! Should be fixed in https://github.com/TheKins/frankenhud/commit/4093756afb7ce45c022ef1cec95f293553dc40a0, let me know.

**Comment by Whurrhurr** [comment]
can confirm it's fixed
