### ISSUE TITLE
[Bug] the "Cancel" button for applying a tool to an item in your backpack overlaps backpack page buttons 41, 42, and 43

### ISSUE THREAD

**Issue by Whurrhurr** [TheKins/frankenhud#106]
Title.
![image](https://github.com/TheKins/frankenhud/assets/33162051/d393ef54-5f50-4c00-a7e4-a0962d1bf5b2)

probably try moving it down and to the right so it's on the opposite side of screen that the "Back (Q)" button is in.

**Comment by Kruphixx** [comment]
Fixed in 1a93925aa62c8a3c8ff44157d542b4c1d6161064, I couldn't seem to put the button in the footer so this will have to do.

![Screenshot 2024-06-29 164039](https://github.com/TheKins/frankenhud/assets/50501742/f7bcb3c8-af02-4a34-a038-79eafc9fbf55)
