### ISSUE TITLE
Investigate optimization issues regarding ShadedBar/ShadedBox

### ISSUE THREAD

**Issue by FlaminSarge** [TheKins/frankenhud#18]
It's possible that our use of ShadedBar/ShadedBox to replace an element's background (such as with the build/destroy/Eureka/Disguise/Taunt menus) is causing clients to freeze momentarily when opening such menus. I need to investigate this and come up with a solution if it is actually occurring.

Any other reports would be helpful.

**Comment by Kruphixx** [comment]
https://github.com/CriticalFlaw/flawhud/issues/361

(Only almost 10 years too late) This is caused by` vgui_cache_res_files 0`, not the use of ShadedBar/ShadedBox itself. Confirmed after testing in game.
