### ISSUE TITLE
Score screen is all kinds of messed up

### ISSUE THREAD

**Issue by DicksMcLong** [TheKins/frankenhud#32]
![frankenhud](https://cloud.githubusercontent.com/assets/13160752/8492920/dba18998-2117-11e5-8839-1c8882fc70b8.jpg)

Everything's kind of smashed as far left as it can go (note the top of the scoreboard where it says (NameScoreStreakPing).

Other than that, I haven't really noticed issues.  The contract menu was a bit smooshed together, but still readable.

**Comment by TheKins** [comment]
Delete your current FrankenHUD install and use the hud_src folder from this Github repo (click "Download Master" to get it).

**Comment by DicksMcLong** [comment]
![frankenhud fixedf](https://cloud.githubusercontent.com/assets/13160752/8496962/ebb3e0d4-213e-11e5-911b-d36fa5e7fa90.jpg)

Oh, pfft.  I thought I'd uninstalled the old version but I left it in.  My mistake.

**Comment by DicksMcLong** [comment]
![frankenhud 2](https://cloud.githubusercontent.com/assets/13160752/8498654/f234876e-214e-11e5-86b0-5841404c4a3b.jpg)


Instead of just making a new issue, I'll just post this here: the end-of-round score screen seems to have the coin icon slightly off.

**Comment by TheKins** [comment]
Fixed.
