### ISSUE TITLE
Weapon pick-up showing improper icons?

### ISSUE THREAD

**Issue by DicksMcLong** [TheKins/frankenhud#34]
![weapon pickup 1](https://cloud.githubusercontent.com/assets/13160752/8686744/ad86c56a-2a4e-11e5-875f-d02c65c7faa7.jpg)
![weapon pickup 2](https://cloud.githubusercontent.com/assets/13160752/8686746/b064e514-2a4e-11e5-98e2-b9b4675e8b09.jpg)

I noticed this while in-game: while selecting a dropped weapon that you can pick up, the menu that shows what the weapon is shows a skull and crossbones.  There also is no button shown for the prompt to pick up the dropped weapon.

**Comment by FlaminSarge** [comment]
For reference, dyou have a screenshot of the stock pickup panel?

**Comment by DicksMcLong** [comment]
It appears as though the skull is there on the stock HUD, which is kind of peculiar.  

![frankenhud 3](https://cloud.githubusercontent.com/assets/13160752/8733722/f7c63c8c-2bca-11e5-8e1d-e421c6d80a52.jpg)
![frankenhud 4](https://cloud.githubusercontent.com/assets/13160752/8733724/f93d814c-2bca-11e5-8b75-3e6b51310247.jpg)

**Comment by FlaminSarge** [comment]
My next question is whether you have the 'health above teammates' option disabled, which is probably the cause.

**Comment by DicksMcLong** [comment]
![frankenhud 5](https://cloud.githubusercontent.com/assets/13160752/8760132/6bf6c0c0-2cd1-11e5-83da-af7539366bf7.jpg)
![frankenhud 6](https://cloud.githubusercontent.com/assets/13160752/8760135/7ae35378-2cd1-11e5-8461-a0b630aa31e6.jpg)

Skull's gone, but the button prompt still doesn't show the key.

**Comment by TheKins** [comment]
I vaguely recall the not showing the key being a conscious decision I made back during the Engineer update. God knows why, though...

**Comment by FlaminSarge** [comment]
It was probably because there wasn't much else you could do on Mouse2 for Engy, so it was just obtrusive. We can totally add it back, but what bugs me is that that's a lowercase 'm' rather than a capital 'm'. I swear that on my end on stock HUD, it's got a capital F rather than a lowercase one.

Also, why did we revert the fonts, again?

**Comment by Kruphixx** [comment]
![20240319130626_1](https://github.com/TheKins/frankenhud/assets/50501742/cd2b5878-5dbb-4349-b770-e1cf0f2f61c9)

Seems fixed already I guess.
