### ISSUE TITLE
Various MvM UI bugs

### ISSUE THREAD

**Issue by DicksMcLong** [TheKins/frankenhud#35]
I did a few MvM games the other day, and caught these GUI bugs.  I have cl_hud_minmode set to 0:

1: No A/B points for Mannhattan, even if they're being capped.
![frankenhud mvm](https://cloud.githubusercontent.com/assets/13160752/8866100/0a92a1f8-317e-11e5-936b-5ef123bbeb06.jpg)

2: Player HUD icons are all pushed together (this is only while they're loading in, not while selecting a class)
![frankenhud mvm 2](https://cloud.githubusercontent.com/assets/13160752/8866113/34e4ea1a-317e-11e5-8c14-d8d27f5dcf34.jpg)

**Comment by FlaminSarge** [comment]
Will examine this when I have a chance.

**Comment by Kruphixx** [comment]
![20240319131314_1](https://github.com/TheKins/frankenhud/assets/50501742/a5772f07-0a65-4234-996c-51f3b89a4778)

Seems to have been fixed already
