### ISSUE TITLE
mp_tournament_readymode 1

### ISSUE THREAD

**Issue by jondpenton** [TheKins/frankenhud#36]
Please add support for mp_tournament_readymode. When it is turned on, frankenhud looks like this: 
![image](https://cloud.githubusercontent.com/assets/3173124/9152425/6f16ef64-3ded-11e5-80b2-3cd92dd3e189.png)

**Comment by FlaminSarge** [comment]
Uh-oh. When it's off, what does it look like? No Scout/class box up top?
