### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by BattleBrisket** [TheKins/frankenhud#44]
Can someone provide me with steps (or a link to steps) that explains how to compile/install from source code contained in the repo?

**Comment by colebob9** [comment]
I just made a quick and easy batch script to build it from source.

https://github.com/colebob9/FrankenHUD-Builder

**Comment by FlaminSarge** [comment]
We'll be reorganizing this repo so that you can clone it directly to tf/custom/frankenhud, but in the meantime colebob9's script is a good way to turn it into a VPK.

**Comment by BattleBrisket** [comment]
Awesome, thank you both for the info.
