### ISSUE TITLE
Unable to see this http://steamcommunity.com/sharedfiles/filedetails/?id=600344323

### ISSUE THREAD

**Issue by TheSammiLord** [TheKins/frankenhud#45]
i run tf2 in fullschreen and my reselution is 1440 X 900
and i don't use any other mods that should make this possible

I did not remember the name of what that is XD

**Comment by BattleBrisket** [comment]
An actual link: http://steamcommunity.com/sharedfiles/filedetails/?id=600344323

![Actual link](http://images.akamai.steamusercontent.com/ugc/368534256073955318/5EA2D0E3D5006EAD76AA4D54E2E15C2D073D2F1A/)
