### ISSUE TITLE
Almost zero functionality in matchmaking

### ISSUE THREAD

**Issue by DicksMcLong** [TheKins/frankenhud#46]
After-action screen is just a blank screen with a "disconnect" button.

That puff of smoke on the right side, in front of the demo?  That's supposed to be a medal or something, and the announcer says "Let's see who's the best" or something like that.

Running the (currently) latest version of Frankenhud on DX 9.0 with cl_hud_minmode 0.

![competitive](https://cloud.githubusercontent.com/assets/13160752/13517401/c0e7b582-e188-11e5-9631-a41bdf09060c.jpg)

**Comment by FlaminSarge** [comment]
Yup, the current hud didn't have the necessary new scoreboard elements. We're working on it, but I'd suggest going back to stock hud during comp tests.

**Comment by DicksMcLong** [comment]
Any updates?  I would really enjoy using FrankenHud in competitive instead of limping along with a hud I'm not used to.

**Comment by FlaminSarge** [comment]
I don't think it's actually a good idea for us to start supporting the Competitive HUD until Valve releases Competitive. They've changed the UI elements almost every single update, and they've pushed out updates almost every day. This means that the HUD gets outdated every day if we try to keep up.

I'll see about making something that's *compatible* with competitive, without skinning competitive, but chances are you'll lose some of the FrankenHUD elements for a while, while competitive stuff moves all the internal stuff around.

**Comment by DicksMcLong** [comment]
Why not pull a Frankenhud?  Last time I checked Rayshud was working pretty well.  You could just keep splicing in what he uses for competitive until you've got your own version going.

**Comment by FlaminSarge** [comment]
That's probably the plan, but it'd again require us to update from that every time Valve changes something.
