### ISSUE TITLE
Round time does not appear on Payload , Attack/Defense , CP , CTF and Special Delivery

### ISSUE THREAD

**Issue by Megaultre** [TheKins/frankenhud#50]
Hi , when i play TF2 with Frankenhud , the round time does not appear on the screen. Here is a screenshot of me playing on Payload in Upward map : 

http://i.imgur.com/kEhJ5s0.jpg

**Comment by FlaminSarge** [comment]
Valve recently changed up a few things with the UI in preparation for competitive. We're going to hold off on updated FrankenHUD until Valve settles on the UI for it, in order to avoid making changes that Valve breaks again. Please bear with us, and use the stock HUD or another HUD in the meantime.

**Comment by Megaultre** [comment]
OK , Thank you
