### ISSUE TITLE
Class switch stays default

### ISSUE THREAD

**Issue by bluekittyyoyo** [TheKins/frankenhud#53]
I have had FrankenHUD in the past and loved it, particularly how clean and non-intrusive the class switching menus were. After the past few updates and a hard drive replacement, I'm installing TF2 and all my previous mods/HUDs. For some reason the class switching menus are the default ones. I have downloaded and re-downloaded several different versions of FrankenHUD and none of them seem to do the trick. I have made absolutely sure the HUD is correctly installed each time.

**Comment by FlaminSarge** [comment]
If I remember correctly, TF2 refuses to load certain HUD files if the HUD's version info doesn't match TF2's (as in https://steamcommunity.com/app/440/discussions/0/365172547948814948/ )

It's possible that this is what's happening.

**Comment by bluekittyyoyo** [comment]
Thank you for the comment! According to that thread as well as some further reading I've done, the UI versions are compatible. Unless the version number is different than 2 since Jungle Inferno, that should not be the problem.

**Comment by bluekittyyoyo** [comment]
Update! After searching around a bit more, I discovered that the files were organized in such a way that TF2 did not recognize certain files to be there. Resources, scripts, and a few other folders/files were put into a folder called "hud_src" and all I had to do was move the contents of that folder into the HUD folder.
