### ISSUE TITLE
Any way to make this work in this day and age?

### ISSUE THREAD

**Issue by ddmlk** [TheKins/frankenhud#54]
Hello. I've decided to try this HUD out on the sole virtue of it not looking like shit, and while the hud itself works(haven't tested it very thoroughly, though), the customization features don't, namely the class pick menus and reverting fonts. I've deleted the mod's font files in an attempt to make it fallback to the default game fonts, and it does indeed fallback, but to Windows fonts! Please note that I'm pretty much a complete idiot when it comes to custom stuff in TF2. Is there any way to make it work, or any chance the author will come back to it?

**Comment by FlaminSarge** [comment]
Closed by #55
