### ISSUE TITLE
Manmelter Crit meter overlaps with Phlog Mmph meter

### ISSUE THREAD

**Issue by NonhumanFromSteam** [TheKins/frankenhud#56]
![Clipboard06](https://user-images.githubusercontent.com/25296372/128213972-2a7a0ac8-c42d-4e42-8362-38a5bacb4b65.jpg)

**Comment by FlaminSarge** [comment]
@Scoutman01 is this consistent with what you see on your end?

**Comment by Scoutman01** [comment]
indeed it does overlap, a potential fix : huditemeffectmeter_engineer > HudItemEffectMeter > change xpos value to c192

the result : 
![20210807203838_1](https://user-images.githubusercontent.com/50184129/128610863-f6616461-34a9-4123-bdde-99ec00913c0a.jpg)

**Comment by FlaminSarge** [comment]
If it solves the issue, go ahead and open a PR and I can merge it, not quite able to go look/test rn.

**Comment by FlaminSarge** [comment]
Fixed by #58
