### ISSUE TITLE
Old scoreboard and killsteak meter

### ISSUE THREAD

**Issue by Scoutman01** [TheKins/frankenhud#63]
Hey i've managed to update the old scoreboard used back in gun mettle update, the current scoreboard is good so what i have in mind is to provide it in extras_src
![20210830152153_1](https://user-images.githubusercontent.com/50184129/131347702-4267b844-4633-4a44-b02b-c1c6eb48939c.jpg)
same thing for the old killstreak meter and it should resolve #26 
![killstreak](https://user-images.githubusercontent.com/50184129/131347847-d90321ae-7403-494e-950f-7d31d66276b5.PNG)

What do you think ?

**Comment by Kruphixx** [comment]
Only a few years too late, added in https://github.com/TheKins/frankenhud/commit/c8c1b949331c1f6db6c136bf4bf05412b6945305.

![20240218233528_1](https://github.com/TheKins/frankenhud/assets/50501742/d4e2c79b-7773-4d5e-b155-09be07370ec9)

![20240218233013_1](https://github.com/TheKins/frankenhud/assets/50501742/4035e4b2-7d53-49e5-acb7-9b50ccd77212)
