### ISSUE TITLE
HUD issue on 2CP Arena maps

### ISSUE THREAD

**Issue by Kruphixx** [TheKins/frankenhud#76]
Resolution: 1920x1080
Operating system: Windows 11

On 2CP Arena maps, the control point HUD overlaps with the arena player count. I would make a pull request but I'm not sure what the best course of action here would be, either changing the position of the player count or doing something to the cp hud?

![20240102145723_1](https://github.com/TheKins/frankenhud/assets/50501742/35e8818b-d619-490a-a35a-548b609abf4b)

**Comment by FlaminSarge** [comment]
Fixed by #78
