### ISSUE TITLE
[Feature Request] Vote Button while in-game

### ISSUE THREAD

**Issue by HeteroChromia420** [TheKins/frankenhud#97]
I feel this should be a thing that needs to be added due to the current reality that is Casual in current year...

**Comment by HeteroChromia420** [comment]
Either that or this is an existing feature but just doesn't work on linux for whatever reason...

**Comment by HeteroChromia420** [comment]
for now i made a bit of a hack fix for my use case and made a modification to my installation of a class quickswitch config, now pressing shift+v opens up the vote menu. keeping this open while i wait for future developments.

**Comment by Kruphixx** [comment]
Sorry but it doesn't seem like anything can be done here and I have no idea why this is even happening. I contacted a friend who's also a linux user and they have the same issue.

This is probably yet another case of spaghetti code.

**Comment by FlaminSarge** [comment]
lmao remove `[$WIN32]` here https://github.com/TheKins/frankenhud/blob/master/resource/gamemenu.res#L1 and we should be set

**Comment by Kruphixx** [comment]
> lmao remove `[$WIN32]` here https://github.com/TheKins/frankenhud/blob/master/resource/gamemenu.res#L1 and we should be set. There's probably other places where this happens, so we should figure out where those match stock TF2 hud vs instances we added on our own. When I tried editing the file thru GitHub's browser editor, it screwed with the line endings/etc. so I'll leave the change to you.

💀 can't believe I missed that. @HeteroChromia420 can you see if that fixes the issue?

I'll look through all files some time to remove all the [$WIN32] to avoid problems like this in the future. well, technically already started doing that one by one.

**Comment by Kruphixx** [comment]
> lmao remove `[$WIN32]` here https://github.com/TheKins/frankenhud/blob/master/resource/gamemenu.res#L1 and we should be set. There's probably other places where this happens, so we should figure out where those match stock TF2 hud vs instances we added on our own. When I tried editing the file thru GitHub's browser editor, it screwed with the line endings/etc. so I'll leave the change to you.

Had a friend test this, the [$WIN32] is not the problem since the default HUD also has this and yet it doesn't happen to them on the default HUD.

![Screenshot 2024-03-17 at 18-57-13 TF2-Default-HUD_#TF2 Files_resource_gamemenu res at master · Hypnootize_TF2-Default-HUD](https://github.com/TheKins/frankenhud/assets/50501742/e4adb26c-752f-4f68-ae6e-49c2cbd4d5de)

**Comment by HeteroChromia420** [comment]
Can confirm, latest git version does *not* fix the underlying problem.

**Comment by Kruphixx** [comment]
> Can confirm, latest git version does _not_ fix the underlying problem.

Should be fixed in https://github.com/TheKins/frankenhud/commit/b598cb6018e40c9341b82459442a1f54833cfdac for real this time, if not I will murder a certain individual. Check if it works for you

**Comment by HeteroChromia420** [comment]
![image](https://github.com/TheKins/frankenhud/assets/56137935/6c08e6f0-d347-4df5-b938-952445135543)
Success!

**Comment by HeteroChromia420** [comment]
Checking if old menu doesn't break this (probably won't but best to check as well)

**Comment by HeteroChromia420** [comment]
Confirmed: Old Menu does not break the fix.

**Comment by FlaminSarge** [comment]
Are you telling me that the line ending issue/encoding issue I ran into when editing on GitHub browser _itself_ was the issue? That's... something.
