### ISSUE TITLE
[Improvement] Brief Description & Preview of customizations/extras

### ISSUE THREAD

**Issue by HeteroChromia420** [TheKins/frankenhud#98]
Title, i feel this would be useful for those who want to know more about what each item does, and how do they look like.

**Comment by Kruphixx** [comment]
Could you explain your request a little more? I'm not sure what you mean by "extra items". Items already have descriptions and stuff when you hover over them in some menus.

**Comment by HeteroChromia420** [comment]
Sure, i'm referring to the #extras folder in particular on the HUD.

**Comment by Kruphixx** [comment]
Oh. Yeah I will do that on the HUD's wiki eventually, similiar to how other huds do it (BudHud, HEX Hud etc.).

**Comment by Kruphixx** [comment]
https://github.com/TheKins/frankenhud/wiki/Customizations

@HeteroChromia420 Done! Let me know if there's anything else that could be added to it. For now I'll keep this open.

**Comment by HeteroChromia420** [comment]
the old menu option was removed? kinda prefered that one over the current one.

**Comment by Kruphixx** [comment]
> the old menu option was removed? kinda prefered that one over the current one.

I think I removed it by accident then forgot to add it back when I was doing some restructuring in the extras directory. I'll add that back later today.

**Comment by Kruphixx** [comment]
> the old menu option was removed? kinda prefered that one over the current one.

Added it back in https://github.com/TheKins/frankenhud/commit/8d69258ed85a47998be3d53d1b9b44b85174ec03, let me know if there's anything else that can be done

**Comment by Kruphixx** [comment]
I guess I'm just gonna close this, any future customizations will be added to the wiki.
