### ISSUE TITLE
Speedometer not working properly

### ISSUE THREAD

**Issue by kp9589kp** [TheKins/frankenhud#99]
the speedometer will show up on screen but thats it. when moving in game you can see them trying to move but its not working or the nurmbers are overlapping to much or somthing im not sure

**Comment by FlaminSarge** [comment]
Screenshot/video/gif please.

**Comment by kp9589kp** [comment]
https://github.com/TheKins/frankenhud/assets/164273729/8afaaad8-09d1-4b3b-9597-ef86a978bc2c

**Comment by Kruphixx** [comment]
Could have something to do with the server settings maybe? Looks like low-gravity, wonder if that somehow messes it up. Unless this happens on "normal" servers too?

**Comment by kp9589kp** [comment]
https://github.com/TheKins/frankenhud/assets/164273729/4680477f-4a27-43db-bbf2-566a24ce7f78

i just opened a map up privately for both of these, when i took the first video i already had the gravity lowered as i was messing around jumping. this video is normal gravity

**Comment by FlaminSarge** [comment]
I suspect something's bugging out in the VMTs for the speedometer, but I have to do some reading on how the 4-digit calc works.

**Comment by kp9589kp** [comment]
well any help with it is much appreciated thank you

**Comment by Kruphixx** [comment]
I might just remake the speedometer from scratch, there's a chance I screwed something up because I pretty much just ported the speedometer from another hud. 

I will also most likely change the font since I feel like the TF2 one isn't very readable.

I like the way it's done in budhud with colored numbers, might try doing that but not sure if it'll fit well with the hud.

**Comment by kp9589kp** [comment]
Funny story for you, i swap between frankenhud and budhud. i'm the one that brought up the speedo in the budhud discord the other day. but as far as using budhuds speedo on frankenhud i think it would work pretty well, just tweak it some like location size or gradient change to fit the hud better maybe, im far from being a coder so take anything i say with a grain of salt lol

**Comment by FlaminSarge** [comment]
I'm down for grafting it in from budhud

**Comment by Kruphixx** [comment]
> I'm down for grafting it in from budhud, looks pretty good and the current one's TF2 default font is a bit too stylized for readability in a speedometer. Maybe TF2Secondary whatever other fonts are available for it?

Any font can be used. I guess TF2Secondary is somewhat better but I'm wondering if it would be better to just go for a "normal" font.

**Comment by Kruphixx** [comment]
https://github.com/TheKins/frankenhud/assets/50501742/7dd033ef-a389-43b9-86ff-aea3b2e554f2

Final result! I couldn't get above 1500 speed but it starts to turn purple after that, and at 3500 speed it turns red. I'll push a commit shortly, let me know if it works fine for you.

**Comment by Kruphixx** [comment]
@kp9589kp Any update on this? Have you checked if the new speedo works properly for you?

**Comment by kp9589kp** [comment]
yes it now works correctly, thank you!
